#!/bin/bash

# PEDIR AL USUARIO POR SU NOMBRE

# 1 MOSTRAR MENSAJE PIDIENDO AL USUARIO SU NOMBRE
echo -n "Cual es su nombre ? "
# 2 LEE EL INPUT DEL USUARIO
read INPUT_USUARIO
# 3 MOSTRAR MENSAJE CON SALUDO AL USUARIO
echo "Saludos Cordiales ${INPUT_USUARIO}"